### ISSUE TITLE
v0.11 - ReferenceError [Error]: window is not defined

### ISSUE THREAD

**Issue by bosticka** [davidmyersdev/vite-plugin-node-polyfills#30] opened 2023-08-07 19:52 UTC
v0.9 builds fine.  Bumping to v0.11 causes this stack with same codebase everywhere else:

node:internal/event_target:1012
  process.nextTick(() => { throw err; });
                           ^
ReferenceError [Error]: window is not defined
    at file:///home/build/block/client/.svelte-kit/output/server/chunks/index3.js:2:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by bosticka** [comment] 2023-08-07 19:53
I tested v0.10 as well and it works.  Issue is with v0.11 only.

Thanks!

**Comment by softwarecurator** [comment] 2023-08-10 22:30
same issue 0.10 works 0.11 causes window to bug out

**Comment by davidmyersdev** [comment] 2023-08-11 21:50
Duplicate of #29 (fixed in `v0.11.1`).

**Closed by davidmyersdev** 2023-08-11 21:50 UTC
