### ISSUE TITLE
i get error after i build ReferenceError: process is not defined

### ISSUE THREAD

**Issue by melsayedgit** [davidmyersdev/vite-plugin-node-polyfills#21] opened 2023-06-17 02:57 UTC
ReferenceError: process is not defined

**Comment by davidmyersdev** [comment] 2023-06-17 21:28
Hey there. 👋  Can you share your Vite config or provide a reproduction for me?

**Comment by isirode** [comment] 2023-06-18 15:40
Hello, I've encountered the same/similar error.

My config was the default one, but I've tried to play with the globals properties (disabling process and global) since I only needed to polyfill 'path'.

It did not worked either way.

```typescript
import { defineConfig } from 'vite'
import { nodePolyfills } from 'vite-plugin-node-polyfills'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    nodePolyfills({
      // To exclude specific polyfills, add them to this list.
      exclude: [
        'fs', // Excludes the polyfill for `fs` and `node:fs`.
      ],
      // Whether to polyfill specific globals.
      globals: {
        Buffer: true, // can also be 'build', 'dev', or false
        global: true,
        process: true,
      },
      // Whether to polyfill `node:` protocol imports.
      protocolImports: true,
    }),
  ],
})
```

My error was slighly different, it was 'Uncaught TypeError: Cannot read properties of undefined (reading 'isTTY')', from this code (from jest-util):
```typescript
var _default =
  !!process.stdout.isTTY && process.env.TERM !== 'dumb' && !_ciInfo().isCI;
exports.default = _default;
```

My context is specific, I am running Mocha tests using [WebDriverIO browser runner](https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-browser-runner).

I do not have this error when I am not using the plugin.

I ended up using `path-browserify` manually, as an alias.

**Comment by davidmyersdev** [comment] 2023-06-19 18:53
Hey @isirode. I still need a reproduction in order to debug this. If you can provide a StackBlitz or CodeSandbox example of this error, I should be able to diagnose the issue and get a fix out.

**Comment by isirode** [comment] 2023-07-19 19:36
Hi, sorry, I had forgotten about it since I did not used it in the end, I will try to provide a reproduction when I have time.

**Comment by davidmyersdev** [comment] 2023-08-06 23:26
I'm closing this since I cannot reproduce it. Please open a new issue if this is still a problem.

**Closed by davidmyersdev** 2023-08-06 23:26 UTC
Labels: missing reproduction
