### ISSUE TITLE
Can this work with fs/promises?

### ISSUE THREAD

**Issue by NoisyMonk** [davidmyersdev/vite-plugin-node-polyfills#25] opened 2023-07-10 21:34 UTC
vite: 4.4.0
vite-plugin-node-polyfills: 0.9.0

I stumbled across this Plugin while trying to solve a "Failed to resolve entry for package "fs"" error and this looks promising. However while this Plugin does fix that first error, I then get the following error. Am I doing something wrong, or is this use case not covered?

![image](https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/25105923/d180cb3f-bfb2-4bd9-b40e-8ed6180b94b8)

![image](https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/25105923/53dc3db0-bc5b-459e-9896-c13115da861a)

**Comment by davidmyersdev** [comment] 2023-08-06 20:03
This is a duplicate of #16. It's not currently supported, but it's on the roadmap for when I have time to get to it. Always happy to review a PR in the meantime though. 😄

**Closed by davidmyersdev** 2023-08-06 20:03 UTC

**Comment by shellscape** [comment] 2024-02-24 02:58
For anyone else who runs across this, add this `resolve` config to your vite config:

```ts
  resolve: {
    alias: {
      'node:fs/promises': 'node-stdlib-browser/mock/empty',
    }
  },
```

(Omit `node:` if you don't have imports using that protocol) That points the `fs/promises` import at the same mock that node-stdlib-browser uses for `fs`.
