### ISSUE TITLE
The plugin breaks nuxi build

### ISSUE THREAD

**Issue by learntheropes** [davidmyersdev/vite-plugin-node-polyfills#41] opened 2023-09-08 19:01 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.17.0
- Nuxt Version:     3.7.1
- CLI Version:      3.8.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/learntheropes/github-anc6tm  
https://stackblitz.com/edit/github-anc6tm
But you need to build it.

### Describe the bug

In a Nuxt 3 application, `vite.config.js` is replaced in `nuxt.config.js` as follows.
```js
import { nodePolyfills } from 'vite-plugin-node-polyfills';

export default defineNuxtConfig({
  vite: {
    plugins: [
      nodePolyfills({
        include: ['buffer', 'util', 'stream', 'crypto'],
      }),
    ],
  },
});
```
However, the plguin breaks `nuxi build` as follows :
```
(inject plugin) rollup-plugin-inject: failed to parse /home/giovanni/Documents/Dev/github-anc6tm/.nuxt/dist/server/server.mjs. Consider restricting the plugin to particular files via options.include

 ERROR  RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)                                                                                      nitro 7:53:52 PM


229:   }
230:   const head = inject(headSymbol);
231:   if (!head && dist.process.env.NODE_ENV !== "production")
                         ^
232:     console.warn("Unhead is missing Vue context, falling back to shared context. This may have unexpected results.");
233:   return head || getActiveHead();


 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)                                                                                                         7:53:52 PM

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Module.error (node_modules/rollup/dist/es/shared/node-entry.js:13726:16)
  at Module.tryParse (node_modules/rollup/dist/es/shared/node-entry.js:14457:25)
  at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:14058:39)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:24623:20) 



 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript) 
```

Accordingly to Nuxt devs, is a plugin issue: https://github.com/nuxt/nuxt/issues/23091#issuecomment-1712098697

**Comment by davidmyersdev** [comment] 2023-09-10 22:42
Hey there, @learntheropes. 👋 It looks like this is due to the global `process` object being polyfilled. You can use the `globals` config option to disable it, and that appears to fix the issue as far as I can tell. Here is what that looks like in your config.

```ts
import { nodePolyfills } from 'vite-plugin-node-polyfills'

export default defineNuxtConfig({
  vite: {
    plugins: [
      nodePolyfills({
        include: ['buffer', 'util', 'stream', 'crypto'],
        globals: {
          process: false,
        },
      }),
    ],
  },
})
```

For what it's worth, this is likely something that should be handled automatically when the `include` and `exclude` options are used, but that is not how they are currently implemented. I'll leave this issue open to track that enhancement.

**Comment by learntheropes** [comment] 2023-09-11 00:00
Thank you, @davidmyersdev !
I confirm that this fixed the issue on my project.

**Comment by DavidDomkar** [comment] 2023-09-11 22:16
Thank you as well. Without this issue, what was going on would never have occurred to me. I would probably add a small note about this to README.md, so others know.

**Comment by lokinz** [comment] 2023-10-11 22:30
`
globals: {
          process: false,
        },
`
Doesn't seem like a solution. I am trying to polyfill process, any ideas?

**Comment by davidmyersdev** [comment] 2023-10-14 21:28
@lokinz can you share an example with your use case?

**Comment by davidmyersdev** [comment] 2023-12-22 20:04
This has been fixed by #63 and is available in [`v0.18.0`](https://github.com/davidmyersdev/vite-plugin-node-polyfills/releases/tag/v0.18.0).

**Closed by davidmyersdev** 2023-12-22 20:04 UTC
Labels: enhancement, help wanted, good first issue

**Comment by paro-paro** [comment] 2023-12-26 16:52
Hi @davidmyersdev 

The new version `v0.18.0` seems like a regression since now I cannot even run the nuxt dev server unless I disable the global process option.

> `globals: { process: false, },`
> Doesn't seem like a solution. I am trying to polyfill process, any ideas?

As pointed out by @lokinz, not polyfilling the process global in build mode did not seem right to me since that is exactly what I need the plugin to do and I was hoping that the new version fixed it.

My use case:

`nuxt` + `web3auth/modal` library

This library needs pollyfils as explained [here](https://web3auth.io/docs/troubleshooting/vite-issues).

Version `0.17.0` of this plugin was allowing me to run at least the dev server but was failing in build mode as explained in this thread.

Latest version now breaks both dev and build modes throwing:

dev: `Missing "./shims/process/" specifier in "vite-plugin-node-polyfills" package [plugin vite:dep-pre-bundle]`
build: `Nuxt Build Error: Missing "./shims/process/" specifier in "vite-plugin-node-polyfills" package`

Here is a [reproduction](https://stackblitz.com/edit/github-yd3jt3?file=nuxt.config.ts)

Any help will be appreciated and thanks for the plugin!! 😄

**Comment by davidmyersdev** [comment] 2023-12-27 05:38
I really appreciate the reproduction, @paro-paro! It looks like a dependency is trying to import `process/` (with a trailing `/`) rather than `process` which leads to the error you're seeing. Would you mind opening another issue for this? I will get a fix together soon.

**Comment by paro-paro** [comment] 2023-12-27 09:48
ohhh that's it... really having the worst time working with this library...

I will definitely open an issue upstream. I understand that I should open a new one here as well (even thou this not seem like a bug within the plugin)?

And thanks a lot for your quick response! 🙏  @davidmyersdev
