### ISSUE TITLE
Nuxt3 - Cannot read properties of null & fs

### ISSUE THREAD

**Issue by trumanjchan** [davidmyersdev/vite-plugin-node-polyfills#51] opened 2023-10-21 01:06 UTC
Hi! I [read](https://github.com/davidmyersdev/.github/blob/9c53a4489d1ad0211696caca1ac66caa58b96fde/CONTRIBUTING.md) I should post this in Discussions but I couldn't find the tab, sorry!

I have this [error](https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility), so I did `bun install -D vite-plugin-node-polyfill` and thought that would import `fs` correctly. I'm still getting this issue where my Nuxtjs3 web app, upon refreshing the page, shows a brief flash of everything being loaded then showing the 500: Cannot read properties of null (reading '__esModule') error pointing at the `import fs from 'fs'` line.

I'm not sure if I imported the plugin correctly into my `nuxt.config.ts` file. I also currently don't have a /plugins directory. I'm using node v18.0.0 and bun as my package manager.

Any help or ideas is much appreciated! Thank you!

<img width="433" alt="Screenshot 2023-10-20 at 5 37 15 PM" src="https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/43284404/85e37c09-c499-4963-913c-be55b6767765">
<img width="500" alt="Screenshot 2023-10-20 at 5 38 02 PM" src="https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/43284404/8948b25c-af60-4c9a-8292-a6b0a20e06ab">
<img width="406" alt="Screenshot 2023-10-20 at 5 38 24 PM" src="https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/43284404/297fec4a-bc61-489a-be54-be75843e1b10">

Currently with `import fs from 'fs'`:
<img width="1333" alt="Screenshot 2023-10-20 at 5 44 10 PM" src="https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/43284404/67dde6bc-4ad2-4170-a8af-64ac3576a1cc">

If I change the import line to `import * as fs from 'fs'`:
<img width="1333" alt="Screenshot 2023-10-20 at 5 45 17 PM" src="https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/43284404/a745bdbe-6dc7-4b54-8e54-ad1edaf6b884">

If I change the import line to `const fs = require('fs')`:
<img width="1331" alt="Screenshot 2023-10-20 at 5 43 30 PM" src="https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/43284404/f77401ed-17fa-4a9a-b7ff-df6130d1c39f">

**Comment by davidmyersdev** [comment] 2023-10-31 22:59
Hello, @trumanjchan. This error is expected because the implementation for `fs` is `null` by default. You can use a package such as `memfs` (or something else depending on your needs) along with the `overrides` config option to polyfill `fs`. See https://github.com/davidmyersdev/vite-plugin-node-polyfills/issues/43 for more info (this is a duplicate of that issue).

**Closed by davidmyersdev** 2023-10-31 22:59 UTC
