### ISSUE TITLE
Failed to resolve module specifier "vite-plugin-node-polyfills/shims/global". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by jsoneaday** [davidmyersdev/vite-plugin-node-polyfills#78] opened 2024-02-08 14:32 UTC
Hello I've created an npm package using your package and I am able to build successfully. However when it runs on browser I see the error given. I suspect there is an issue in my vite.config.ts file but not sure what it is. Here's my file

`import { defineConfig } from "vite";
import wasm from "vite-plugin-wasm";
import { nodePolyfills } from "vite-plugin-node-polyfills";
import path from "path";

export default defineConfig({
  resolve: {
    alias: {
      process: "process/browser",
      path: "path-browserify",
      stream: "stream-browserify",
      os: "os-browserify",
    },
  },
  plugins: [
    wasm(),
    nodePolyfills({
      // To exclude specific polyfills, add them to this list.
      exclude: [
        "fs", // Excludes the polyfill for `fs` and `node:fs`.
        //"stream",
      ],
      // Whether to polyfill specific globals.
      globals: {
        Buffer: true,
        global: true,
        process: true,
      },
      // Whether to polyfill `node:` protocol imports.
      protocolImports: true,
    }),
  ],
  build: {
    manifest: true,
    minify: true,
    reportCompressedSize: true,
    lib: {
      entry: path.resolve(__dirname, "src/main.ts"),
      fileName: "main",
      formats: ["es", "cjs"],
    },
    target: "esnext",
    rollupOptions: {
      external: [
        "vite-plugin-node-polyfills/shims/buffer",
        "vite-plugin-node-polyfills/shims/global",
        "vite-plugin-node-polyfills/shims/process",
      ],
    },
  },
});
`

**Comment by andriirak** [comment] 2024-02-09 08:30
have the same issue for my linked package
![image](https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/74956015/4dbe69e1-e77b-40aa-ae1a-690e0eb5bddf)

**Comment by davidmyersdev** [comment] 2024-02-09 23:45
@jsoneaday it looks like you are externalizing the shims for `buffer`, `global`, and `process`. Without a full reproduction, I can't diagnose the problem or provide a fix.

**Comment by bompi88** [comment] 2024-04-10 12:42
> have the same issue for my linked package ![image](https://private-user-images.githubusercontent.com/74956015/303594523-4dbe69e1-e77b-40aa-ae1a-690e0eb5bddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTE1NjAsIm5iZiI6MTcxMjc1MTI2MCwicGF0aCI6Ii83NDk1NjAxNS8zMDM1OTQ1MjMtNGRiZTY5ZTEtZTc3Yi00MGFhLWFlMWEtNjkwZTBlYjViZGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEyMTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZmU2ZmI2ZjVmN2FhYzgyNjBmNjQ2MDJmZTM4NzU2MmI1MjQ5MjhhYjY0MmMwNjk3N2Q2MzllZTQ4YTM1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j2LviEKNsAN5zEmv_BbA8OeINF0Ge83xj77WoW2HK8k)

Adding `vite-plugin-node-polyfills` as dependency to the linked package somehow worked, but it is not ideal. I suspect it is because of the linking and rollup is looking for the package in the wrong context? 🤯

**Comment by patbeqo** [comment] 2024-04-25 16:23
+1 happening on version 0.21.0. Works fine on version 0.19.0

**Comment by JordanBerger** [comment] 2024-07-03 22:57
I came across this today and was able to resolve it by telling the plugin NOT to polyfill process:
```typescript
nodePolyfills({
  globals: {
    // Don't polyfill these globals
    process: false,
    Buffer: false,
  },
}),
```

**Comment by wesbiggs** [comment] 2024-08-23 14:02
Downgrading this plugin to 0.17.0 fixed this error for me.

**Comment by chitter99** [comment] 2024-10-03 20:05
> Downgrading this plugin to 0.17.0 fixed this error for me.

Have the same issue, downgrading solve the problem as well... Let me know if you can help with this issue

**Comment by davidmyersdev** [comment] 2024-10-17 03:21
I'm closing this for now. If a reproduction of the issue is provided, I'll reopen it.

**Closed by davidmyersdev** 2024-10-17 03:21 UTC
Labels: missing reproduction

**Comment by susnux** [comment] 2025-01-22 10:20
@davidmyersdev we can reproduce this. The problem happens if you share a vite configuration:
So you get a dependency tree like this:

- app-package
  - vite-config-package
    - vite-plugin-node-polyfills

You can check this for example on this project (`npm ci && npm run build`): https://github.com/nextcloud/polls/commit/f86aa388b05199feb8b2ba8f690f714c88977420

I guess the problem here is that the dependencies are stored like:
- app
  - library
  - config
    - polyfill plugin

In this case the library needs to access the node modules of the sibling. Probably the safest solution would be to follow the vite plugin guide and use custom resolve ids `\0node-polyfill/shims/...` and also implement the `load` hook for the plugin.

Or just have a `resolveId` in the plugin that returns the absolute path id so it is always resolved.

---

We use this workaround in our shared config:
```ts
	resolve: {
		alias: [
			{
				find: /^(vite-plugin-node-polyfills\/shims\/.+)/,
				replacement: '$1',
				customResolver(source) {
					return import.meta.resolve(source).replace(/^file:\/\//, '')
				},
			},
		],
	},
```
