### ISSUE TITLE
When vite define contains process.env: xx, process polyfill will fail

### ISSUE THREAD

**Issue by winixt** [davidmyersdev/vite-plugin-node-polyfills#71] opened 2024-01-11 13:39 UTC
```js
import { defineConfig } from 'vite'
import { nodePolyfills } from 'vite-plugin-node-polyfills'

// https://vitejs.dev/config/
export default defineConfig({
  define: {
    "process.env.A": 1,
  },
  plugins: [
     nodePolyfills({
       globals: {
          process: true,
       },
    }),
  ],
})
```

![image](https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/20717402/97a151ea-3976-4bba-975a-54e682421227)

**Comment by davidmyersdev** [comment] 2024-01-14 18:17
Hey @winixt. Would you mind adding a reproducible example via Stackblitz or similar?

**Comment by davidmyersdev** [comment] 2024-10-17 03:20
I'm closing this for now. If a reproduction of the issue is provided, I'll reopen it.

**Closed by davidmyersdev** 2024-10-17 03:20 UTC
Labels: missing reproduction
