### ISSUE TITLE
Plugin not working with Svelte

### ISSUE THREAD

**Issue by aryzing** [davidmyersdev/vite-plugin-node-polyfills#34] opened 2023-08-16 14:05 UTC
Just tried setting up a very vanilla Svelte app with `pnpm create vite my-app --template svelte-ts` and added the `vite-plugin-node-polyfills` to handle some libs using Node.js functionality. Seems like it's not working, `Buffer` is undefined.

I've created this repro to aid with debugging,

https://github.com/aryzing/repro-node-polyfill-not-working

Is the config incorrect or is it not working as expected?

**Comment by davidmyersdev** [comment] 2023-08-17 04:50
Duplicate of #22 (fixed in `v0.11.2`). Thanks again for the reproduction!

**Closed by davidmyersdev** 2023-08-17 04:50 UTC
